name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  REGION: us-central1
  SERVICE: workshop5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Decode and authenticate with service account
      run: |
        echo "${{ secrets.GCP_SA_CREDENTIAL_JSON }}" | base64 -d > ${{ runner.temp }}/gcp-key.json
        gcloud auth activate-service-account --key-file=${{ runner.temp }}/gcp-key.json
        gcloud config set project ${{ vars.PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE }} \
          --source . \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --project ${{ vars.PROJECT_ID }}
